In [1]:
import pathlib
import numpy as np
import os


In [2]:
ori_view_path = pathlib.Path("q_e/")
ori_view_num_pathes = list(ori_view_path.glob("*"))

In [3]:
output = "q_e_noise_1mm"
rng = np.random.default_rng()
one_mm = 2.5/1500
sd = one_mm*3

d_a = 0
for i in range(len(ori_view_num_pathes)):
    tsvs = list(ori_view_num_pathes[i].glob("*.csv"))
    for j in range(len(tsvs)):
        P_mat = np.loadtxt(str(tsvs[j]), delimiter="\t")
        a = -np.dot(P_mat[0:3, 0:3].T, P_mat[0:3, 3])
        diff = np.random.multivariate_normal((0,0,0), np.diag((1,1,1))*sd**2)
        P_mat[:3,3] += diff
        os.makedirs(os.path.join(output, ori_view_num_pathes[i].name), exist_ok=True)
        np.savetxt(os.path.join(output, ori_view_num_pathes[i].name, tsvs[j].name), P_mat, delimiter="\t")


In [94]:
os.path.join(output, ori_view_num_pathes[i].name)

'q_e_noise_1mm\\view_mat_64'

In [81]:
np.abs(diff) < sd*2

array([ True,  True,  True])

In [19]:
np.random.multivariate_normal((0,0,0), np.diag((1,1,1)))

array([-0.30038239,  0.08103092,  0.05822081])

In [20]:
np.diag((1,1,1))*one_mm**2

array([[0.00027778, 0.        , 0.        ],
       [0.        , 0.00027778, 0.        ],
       [0.        , 0.        , 0.00027778]])